spring:
  cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: e02b1d3d-73b0-4c07-b7fe-35b2745810ea
        credential:
          client-id: aea554f2-1795-482a-a62d-d6d5bc530b2c
          client-secret: hqC8Q~mVF63fjmbjNiySvIBKRKvHS5xT2TYNRaIw
server:
  port: 8080
  forward-headers-strategy: native